apiVersion: v1
kind: ConfigMap
metadata:
  name: ad-notifier-config
data:
  config.yml: |
    notifier:
      worker_queue_count: 15
      worker_subscription_count: 10
    tarantool:
      servers:
        {{- toYaml $.Values.tarantoolServers | nindent 8 }}
      timeout: 5s
      reconnect_interval: 1s
    sender:
      template_folder: "internal/sender/templates"
    features:
      - "street_id"
      - "house"
      - "price"
      - "price_m2"
      - "rooms"
      - "floor"
      - "year"
      - "m2_main"
    rest:
      port: {{ $.Values.service.internalPort }}
      read_timeout: 10s
      write_timeout: 10s
      max_header_bytes: 1048576
